@startuml

skinparam handwritten true
skinparam titleBorderThickness 2
skinparam titleBackgroundColor AliceBlue

title
    适配器模式（基于类）
end title

Client --> Target : uses >

interface Target{
    + targetMethod1()
    + targetMethod2()
}

class Adapter{
    + targetMethod1()
    + targetMethod2()
}

class Adaptee{
    methodA()
    methodB()
    methodC()
}

Adapter .left.|> Target : > implements

Adapter -right-|> Adaptee : > extends

legend right
    类适配器模式（使用继承）
endlegend

@enduml