@startuml

skinparam handwritten true
skinparam titleBorderThickness 2
skinparam titleBackgroundColor AliceBlue

title
    模板模式
end title

abstract class AbstractClass{
    # method1()
    # method2()
    # method3()
    + templateMethod()
}

class ConcreteClass extends AbstractClass {

    # method1()
    # method2()
    # method3()

}

@enduml