@startuml
together {

   interface Aggregate{
        + iterator()
   }

   interface Iterator<T>{
        + boolean hasNext()
        + T next()
   }

}

Aggregate -right-> Iterator : Creates ▶

together {

    class BookShelf implements Aggregate{

        + iterator()

    }

    class BookIterator<Book> implements Iterator{
        - BookShelf bookShelf
        + boolean hasNext()
        + Book next()
    }

}


BookIterator -left-o BookShelf
' BookShelf --> BookIterator : Creates ▶

@enduml